name: Solidity docs (WIP) # TODO: Change name

on:
  pull_request:
  push:
    branches:
      - releases/mainnet/solidity/**
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  docs-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './solidity/contracts/**'
              - './.github/workflows/solidity-docs.yml'

  # This job will be triggered for PRs which modify contracts. It will generate
  # the archive with contracts documentation in Markdown and attatch it to the
  # workflow run results. Link to the archive will be posted in a PR comment.
  # The job will also be run after manual triggering and after pushes to the
  # `releases/mainnet/solidity/**` branches.
  contracts-docs-publish-preview:
    name: Publish preview of contracts documentation
    needs: docs-detect-changes
    if: |
      github.event_name == 'pull_request'
        || github.event_name == 'push'
        || github.event_name == 'workflow_dispatch'
    uses: keep-network/tbtc-v2/.github/workflows/reusable-solidity-docs.yml@document-contracts-gitbook #TODO: change to `@main`
    with:
      projectSubfolder: /solidity
      # We need to remove unnecessary `//` comment used in the `@dev`
      # section of `BitcoinTx` documentation, which was causing problem with
      # rendering of the `.md` file. We do that by executing
      # `sed -i ':a;N;$!ba;s_///\n//\n_///\n_g'` on the problematic file. The
      # command substitutes `///` + newline + `//` + newline with just `///` +
      # newline and does this in a loop.
      preProcessingCommand: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol
      publish: false
      # destinationRepo: michalinacienciala/experimental
      # destinationFolder: ./docs/app-development/api-docs/tbtc-v2
      # destinationBranch: test-contracts-documentation
      # userEmail: michalina.cienciala@akena.co
      # userName: michalinacienciala
      commentPR: true
      debug: true
    # TODO: remove secrets, won't be needed when publish = false
    secrets:
      githubToken: ${{ secrets.TEST_DOCS_GITHUB_TOKEN }}

  contracts-docs-publish:
    name: Publish contracts documentation
    needs: docs-detect-changes
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/solidity/')
    uses: keep-network/tbtc-v2/.github/workflows/reusable-solidity-docs.yml@document-contracts-gitbook #TODO: change to `@main`
    with:
      projectSubfolder: /solidity
      # We need to remove unnecessary `//` comment used in the `@dev`
      # section of `BitcoinTx` documentation, which was causing problem with
      # rendering of the `.md` file. We do that by executing
      # `sed -i ':a;N;$!ba;s_///\n//\n_///\n_g'` on the problematic file. The
      # command substitutes `///` + newline + `//` + newline with just `///` +
      # newline and does this in a loop.
      preProcessingCommand: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol
      # TODO: change publish to true, uncomment other params below, change branch to `main`
      publish: false
      # destinationRepo: threshold-network/threshold
      # destinationFolder: ./docs/app-development/api-docs/tbtc-v2
      # destinationBranch: test-contracts
      # userEmail: thesis-heimdall@users.noreply.github.com
      # userName: Heimdall
    secrets:
      githubToken: ${{ secrets.THRESHOLD_DOCS_GITHUB_TOKEN }}
