name: Generate and push Solidity API documentation

on:
  workflow_call:
    inputs:
      projectSubfolder:
        description: "A root's subfolder containing the `contracts` folder and
          the Yarn / Hardhat configuration. Leave empty ('') if the project
          config resides in the root. If config resides in a subfolder, provide
          the subfolder name/path, without leading `.` and ending `/`. For
          example, type `/v2/solidity` if the path to the `contracts` folder is
          `./v2/solidity/contracts`."
        type: string
        required: false
        default: ""
      removeTrailingSpacesInComments:
        description: "True if you want to remove space characters between `///`
          and a comment text in the Solidity files, before generating `.md`
          files. This may be needed to improve the look of the lists in the
          generated files."
        type: boolean
        required: false
        default: true
      preProcessingCommand:
        description: "An optional additional bash command to be executed before
          transforming the Solidity files to an HTML file."
        type: string
        required: false
      publish:
        description: "True if you want to push the generated file(s) to the
          destination repository."
        type: boolean
        required: false
        default: true
      destinationRepo:
        description: "A name of the repository where the generated Solidity docs
          will be pushed to. Required if `publish=true`."
        type: string
        required: false
      destinationFolder:
        description: "A path in the destination repository where the generated
          Solidity docs will be pushed to. For example, `./docs-api/tbtc-v2`."
        type: string
        required: false
        default: "."
      destinationBranch:
        description: "A branch on the destination repository where the generated
          Solidity docs will be pushed to (must exist)."
        type: string
        required: false
        default: "main"
      userEmail:
        description: "The email address of a GitHub user associated with the
          `githubToken` secret. Will be used to sign commits. Required if
          `publish=true`."
        type: string
        required: false
      userName:
        description: "The name of the GitHub user associated with the
          `githubToken` secret. Will be used to sign commits. Required if
          `publish=true`."
        type: string
        required: false
      commentPR:
        description: "True if you want to add a comment with the path to the
          generated files in the PR invoking the workflow. If the workflow is
          not triggered by the `pull_request` event, having this input set to
          `true` will not brake the execution."
        type: boolean
        required: false
        default: false
      debug:
        description: "True if you want to see the artifacts generated on various
          stages of workflow execution in the GH run details."
        type: boolean
        required: false
        default: false
    secrets:
      githubToken:
        description: "A GitHub API token for the destination directory. Should
          have `repo` scope. Required if `publish=true`."
        required: false

jobs:
  docs-generate-html-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .${{ inputs.projectSubfolder }}
    steps:
      - uses: actions/checkout@v3

      # In this step we modify the format of the comments in the Solidity
      # contracts files. We do that because our original formatting is not
      # processed by Docgen in the way we would like.
      # To nicely display lists (like the list of requirements) we need to
      # remove multiple space chars after the `///` comment. We do that by
      # executing `sed 's_///[[:blank:]]*_///_'` on all contracts files, which
      # substitutes `///` + 0 or more spaces/tabs with just `///`.

      - name: Prepare contract files for further processing
        if: inputs.removeTrailingSpacesInComments
        shell: bash
        run: |
          find ./contracts \
            -name "*.sol" \
            -type f \
            -exec sed -i 's_///[[:blank:]]*_///_' {} \;

      - name: Execute additional command
        if: inputs.preProcessingCommand != null
        shell: bash
        run: ${{ inputs.preProcessingCommand }}

      - name: Export artifacts
        if: inputs.debug == true
        uses: actions/upload-artifact@master
        with:
          name: contracts-after-preprocessing
          path: .${{ inputs.projectSubfolder }}/contracts

      # We may need this step in case we execute the workflow in a project
      # that has a dependency to `@summa-tx/relay-sol@2.0.2` package, which
      # downloads one of its sub-dependencies via unathenticated `git://`
      # protocol. That protocol is no longer supported. Thanks to this step
      # `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        shell: bash
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        shell: bash
        run: yarn install --frozen-lockfile

      # Generates `.md` file(s) based on config in the `hardhat.config.ts`.
      - name: Build Markdown docs
        run: yarn run hardhat docgen

      - name: Export artifacts
        if: inputs.debug == true || inputs.commentPR == true
        uses: actions/upload-artifact@master
        with:
          name: contracts-final-output
          path: .${{ inputs.projectSubfolder }}/generated-docs

      - name: Push generated docs to the specified repository
        if: inputs.publish == true
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.githubToken }}
        with:
          source_file: .${{ inputs.projectSubfolder }}/generated-docs
          destination_repo: ${{ inputs.destinationRepo }}
          destination_folder: ${{ inputs.destinationFolder }}
          destination_branch: ${{ inputs.destinationBranch }}
          user_email: ${{ inputs.userEmail }}
          user_name: ${{ inputs.userName }}
          commit_message: Update documentation via https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id}}

      - name: Post preview URL to PR
        if: | # inputs.publish == true &&
          inputs.commentPR == true
            && startsWith(github.ref, 'refs/pull')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Solidity API documentation preview available in the artifacts of the https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id}} check.'
            })
